### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by runoob-tan6** [chiuxingxiang/Django-Blog#2]
TypeError at /admin/xadmin/userwidget/add/
render() got an unexpected keyword argument 'renderer'

**Comment by real-qiuxingxiang** [comment]
xadmin的问题

解决：
1.进入xadmin安装路径，编辑xadmin/views/dashboard.py，增加 `renderer=None`
`def render(self, name, value, attrs=None, renderer=None):`
